{% set version = "2.0.13" %}

package:
  name: bob.ip.color
  version: {{ version }}

source:
  fn: bob.ip.color-{{ version }}.zip
  md5: d1e076c699b70746ce4c491a5b5d16cf
  url: https://pypi.io/packages/source/b/bob.ip.color/bob.ip.color-{{ version }}.zip

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - cmake
    - pkg-config
    - boost 1.61.*

  run:
    - python
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - boost 1.61.*

test:
  commands:
    - nosetests -sv bob.ip.color

  imports:
    - bob
    - bob.ip
    - bob.ip.color

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Color Conversion Utilities of Bob

extra:
  recipe-maintainers:
    - 183amir
